### ISSUE TITLE
Theme demo is broken with latest Hugo version

### ISSUE THREAD

**Issue by digitalcraftsman** [wd/hugo-fabric#2]
Hello @wd,

the [demo of the fabric theme](https://themes.gohugo.io/theme/after-dark/) on the theme site if broken. Hugo v0.20.* changed the way how partials are handled. In the head of your HTML pages you're including a partial containing configurable CSS. However, with the newest version of Hugo you've to mark the partial explicitly as safe.

This issue will be fixed by #1. I just created issue to underline issues that are solved by the PR.

Cheers,
Digitalcrafsman

**Comment by wd** [comment]
Thanks. I've merged.
